server {
    listen 80;
    # >>> TROQUE seudominio.com.br pelo SEU domínio real (duas vezes abaixo) <<<
    server_name seudominio.com.br www.seudominio.com.br;

    client_max_body_size 10M;   # permite upload de imagens de produtos

    location /static/ {
        alias /var/www/royal/static/;
        expires 7d;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/royal/royal.sock;
    }
}
